### ISSUE TITLE
[Enhancement] Native Compatibility Suggestions

### ISSUE THREAD

**Issue by ElvenChaos** [thraaawn/BonsaiTrees#1]
Even though saplings can be added manually, it may be good to add native support for a few particular mods:

1. Tinker's Construct (Slime Saplings): Popular mod, unique "trees" that would be an aesthetic twist as a bonsai.
2. Natura: Semi-popular with some wonderful trees. Special support would need to be added for the bloodwood sapling, which goes on a ceiling. Upside-down bonsais please!
3. Plants: An up-and-coming mod that adds a few of its own trees. It doesn't require any special support, but would be nice to have integrated automatically.
4. Rainbow Oaks: Adds one tree that has a rainbow gradient pattern. Some special support might be required.

**Comment by thraaawn** [comment]
- Tinkers Construct Saplings ✔️ 
- Natura Overworld Trees ✔️ 
- Natura Nether Trees: We'd first need a feature to let certain sapling require certain conditions, i.e. they can only be used when the Bonsai Pot itself is in the Nether.
- Plants: I'll take a look soon.
- Rainbow Oaks: It would probably look always the same since the leave block positions are always the same. Maybe try this with a simple JSON integration and if it works create a Pull Request?
