### ISSUE TITLE
2.1.0.1 crashing 1.15.2 client on startup

### ISSUE THREAD

**Issue by kreezxil** [thraaawn/BonsaiTrees#143]
https://pastebin.com/VGzerY2A

**Comment by davenonymous** [comment]
I can't imagine how this can happen to be fair. It must be some weird mod interaction.

This code is triggered by the ColorHandlerEvent.Block event.
The [line](https://github.com/thraaawn/BonsaiTrees/blob/fba0fdef2b958fe097a2cf23f079966219908db3/src/main/java/com/davenonymous/bonsaitrees2/misc/PotColorizer.java#L33) that's triggering the message causing the error provides two existing values, the color and the block. Both are non null. The only thing that could be the problem is the delegate property on the block instance: Minecraft is doing this when registering a blockcolor: ```this.colors.put(block.delegate, blockColor);```
Not sure why that would be empty at that point.

**Comment by davenonymous** [comment]
I am unable to reproduce this. Need more information.

**Comment by kreezxil** [comment]
you can close this, because the release you made 2 days ago fixed it. And
if you didn't do anything, I blame forge.
