### ISSUE TITLE
(1.12.2) Add config option to disable tree rendering

### ISSUE THREAD

**Issue by N1ghthauq** [thraaawn/BonsaiTrees#204]
I just got done adding a config option to my custom build of tinkers' construct so that I could turn off the items in the smeltery so i could make mega large smelteries without dropping FPS.

I've got so many bonsai pots that I go from have roughly 160 FPS to 30 FPS. I notice that the source code is no longer on here. If you could give me that I will do it myself or if you feel happy to help do it for me!

Thank you!

**Comment by Konicai** [comment]
It would be great if this could happen. I haven't used the compact machines mod, however I've read that putting your bonsais in a compact machine removes the fps issue because they stay loaded without being rendered. 

@N1ghthauq , do you have your custom build of tinker's available? 

Update: I was able to use [StopRender](https://www.curseforge.com/minecraft/mc-mods/stop-render) with org.dave.bonsaitrees.tile.TileBonsaiPot in its config to disable the TESR.
