### ISSUE TITLE
Add Biomes O'Plenty compatibility?

### ISSUE THREAD

**Issue by FuuNoKamiOka** [thraaawn/BonsaiTrees#244]
I see in the description it says there was a fix for the Maple trees but I'm trying to use the bonsai's for Magic trees and it doesn't work. Is there a chance BoP will be fully compatible in the future?

**Comment by Slickson77** [comment]
I saw that and experienced the same issue, they don't work but Curseforge says the mod is up to date .... but it isn't, at least in my case.  For some reason the "R" file is not being recognized as the latest.  I bet your file is also the 3.0.0 one and not the 3.0.1.  The only way to fix this right now is to download the file manually and drop it in your mod folder.  Make sure to delete the old file from your mod folder and also make sure to NOT do what curseforge suggests and update the mod after you put the 3.0.1 file in, because it will want you to do that.

**Comment by davenonymous** [comment]
Thanks for the help @Slickson77 !
