### ISSUE TITLE
Question: new dimension in bonsaitrees3

### ISSUE THREAD

**Issue by UdoMorgenstern** [thraaawn/BonsaiTrees#247]
Why does version Bonsai Trees 3 v3.0.1 and higher adds the new dimension called bonsaitrees3:growtown? 
- Forcing the world running under experimental settings
- Teleporting into this dimension will generate structures from other mods
- can't find any setting to disable this "feature"

related commit:
https://github.com/thraaawn/BonsaiTrees/commit/9420f4cbb7dcfc4ffcf43d712e2868730975eb2f

quote: "It might burn your world to the ground with it. You have been warned."
guess this should not be enabled by default?

**Comment by davenonymous** [comment]
It's a dimension that can be used to generate the model json files.

You know a way to make dimensions optional via config? I couldn't find it.
Or how to prevent modded structures from being generated? Is that possible by now?

Every mod that adds a dimension causes that warning dialog to appear, use [Shutup Experimental Settings!](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings) to get rid of it.

That message relates to the command used to generate the trees there.

How does it bother you? What did you intend to do when you teleported there? How did you teleport there without being opped or in creative mode?

**Comment by UdoMorgenstern** [comment]
correct "Every mod that adds a dimension causes that warning", but this mod does not need it own dimension for normal gameplay proposes.

"How does it bother you?"
- A normal player does not need to generate model json files
- having a new dimension cost cpu time, even very little
- this should be an optional feature only, never be part of a release version

"You know a way to make dimensions optional via config? "
- most likely not, hence the solution is to keep this feature in a separate branch for development proposes only

"Or how to prevent modded structures from being generated? Is that possible by now?"
- unclear to me, dimension should not be available in normal game mode in the first time.

"What did you intend to do when you teleported there? How did you teleport there without being opped or in creative mode?"
- checked it out put of interest
- of course we used commands to get there.

PS: I know, looking at the commit, that you put a lot of effort into this part. But consider if a normal player needs this feature, putting a additional strain on a PC, or in our case server. The community on our server really like this mod and it would be a same if we had to remove it because of this issue.

**Comment by davenonymous** [comment]
- Pack devs need to generate model files. There needs to be an easy way to generate model files. Adding support for other mods is the single most requested feature for this mod. This command allows you to do that yourself.
- The dimension is never used or even generated if you don't load it up first. No CPU impact at all, except a few ms during load time.
- I can't make it an optional feature as dimensions can not be optional. The only way would be to create a separate mod...
- If I keep it in a separate branch then pack makers and others wanting to create mod support will not have access to it.
- A normal player isn't able to get there in the first place.

There are good reasons for having it, not many for not having it. I honestly can't think of a *good* reason against it besides the optional dependency on the Shut Up Experimental Settings mod. There is simply nothing else that impacts players in any way because there is another dimension registered.

**Comment by UdoMorgenstern** [comment]
"The dimension is never used or even generated if you don't load it up first."
Reason I saw this dimension in the first place was that I checked the load using /forge tps, which listed the dimension, this proves that is it generated and loaded. 

Closing Ticket as this is and intended behavior, and questions are clarified.
