### ISSUE TITLE
You need to have the permission to send server commands, i.e. be an Operator.

### ISSUE THREAD

**Issue by raziel23x** [thraaawn/BonsaiTrees#77]
_Originally posted by @thraaawn in https://github.com/thraaawn/BonsaiTrees/issues/63#issuecomment-429521607_

How do you give OP settings in a Single player game then tell me how to do this because I went into the Single player world and typed /op and i get the message this is not a unknown command so nope cant do this command in a single player game and why would i need to have to have the permission to send server commands, i.e. be an Operator in a single player game which i am using to do the command in

you do not get a console window to give /op or /deop when your in single player game you should only have to have cheats enabled which i do and that should give you full access to everything

**Comment by thraaawn** [comment]
For me this works out of the box in single player when cheats are enabled (not sure what happens if you open to Lan though). You are the first to have an issue with this. Maybe not assume the dev did not even test his own mod? There is no reason to get impatient or rude. There was also no reason at all to open a new issue for this.

So. Do you want me to actually look into this and fix your problem?
Then you need a) to provide more reliable steps in a mostly vanilla world to reproduce this, since I can't with the info you've given so far. 
b) I'm also curious what you are expecting the command to do for you - did you add new tree-types and specified their worldgen methods? Otherwise the command won't do anything for you.

**Comment by gaminggirl** [comment]
Having same problem, cheats are on but can't do the command because I don't hae permission in a single player world. Also would love to know how to become an op in single player. Trying to dev a mod pack and want to add a couple of trees from a not supported mod.
