### ISSUE TITLE
Dirt not showing

### ISSUE THREAD

**Issue by aaronbekir** [thraaawn/BonsaiTrees#83]
**Bonsai Trees version**1.1.1-b138: (latest version on Curse)
**Forge version**unknown:
**I am not using Optifine**Correct:
**Link to Crashlog**: Doesn't Crash
**Screenshot (if possible)**: Can't get to work.

**Description of the problem including expected versus actual behavior:**

When placing any form of Dirt or Grass in the Bonsai Pot (both normal and hopping), no visual shows of the dirt or item.

**Steps to reproduce:**

Have reinstalled mod fresh from Curse.

**Comment by codetaylor** [comment]
Pretty sure this is caused by the use of `GlStateManager.pushAttrib()` and `GlStateManager.popAttrib()`.

The pop attrib doesn't work properly. I just debugged a very unpredictable rendering issue in one of my mods and this was the culprit.

https://github.com/thraaawn/BonsaiTrees/search?q=GlStateManager.pushAttrib%28%29%3B&unscoped_q=GlStateManager.pushAttrib%28%29%3B

Hope this helps.

**Comment by codetaylor** [comment]
This is the issue referenced by the JavaDoc on the attrib methods:

https://github.com/MinecraftForge/MinecraftForge/issues/1637
