### ISSUE TITLE
[Config Request] Disable Bonsai Growth Render

### ISSUE THREAD

**Issue by Grygon** [thraaawn/BonsaiTrees#95]
Been using the mod with SF4 and loving it so far. Unfortunately, maybe loving it a bit too much--due to the resource dependency in SF4, I've got 400 bonsais placed growing resources, which is causing the FPS on my computer to drop pretty heavily due to single-core CPU load. 

My guess as to what's causing this is the fact that there's 400 different models, each changing per frame/tick due to their growth.  I'd love to see a client-side config option added which could disable this rendering, and just show the fully grown tree instead, using WAILA for percentage growth if someone wants to watch that. It wouldn't be as nice, but it would make the sort of large-scale farms necessary in SF4 much more doable. Thanks!

**Comment by thraaawn** [comment]
It should not be necessary to disable glScale calls to improve performance. I'd rather optimize more than clutter the config with more options.
The problem is the way the scaling etc is calculated. That can be improved, it just never was a real issue. 400 bonsai pots are not normal. Rarely will people have more than 200 of them visible at the same time.

Anyway, after caching the size calculations for the given tree and soil type, which should make the PR obsolete, to really see an improvement in rendering for more than 256 bonsais, we'd have to switch from display lists to VBOs. Which is a bit more difficult.

Sorry, I'm not going to pull the PR, I want to improve this properly instead of just disabling it.

**Comment by Grygon** [comment]
I disagree that 400 of them is too absurd, with the release of SF4 and the various new types of trees added that's only 8 of each. Plus, even when cutting out unnecessary types and scaling down to 6 of each (roughly 240), I'm getting approximately the same results--about 20-25 fps without this option, but 35-40 with it.

That being said, if you're working on this issue then yeah, there's no need for the PR. I just hadn't seen any work being done here, and figured this would be a quick and easy fix that could help some people.

**Comment by nicholasbertolissi** [comment]
>doesn't want to simply add an option to disable
>wants to fix it instead of removing it
>never fixed it

Hey! here from the future. Still an issue lmao

**Comment by nicholasbertolissi** [comment]
Also when changing the game rendering from fancy to fast im still able to see thru the leaves. so many this will help you on your journey to optimize this.
